### ISSUE TITLE
New member request

### ISSUE THREAD

**Issue by edtiss-scotgov** [ScotGovAnalysis/welcome#83]
### To join the organisation, please confirm the following:

- [X] I am a current employee of the Scottish Government
- [X] I have read and understand the [user responsibilities](https://scotsconnect.sharepoint.com/sites/StatisticsGroup-Org-SG/SitePages/GitHub-User-Responsibilities.aspx) for using GitHub in Scottish Government
- [X] I have read the guidance in the [welcome](https://github.com/ScotGovAnalysis/welcome) repo
- [X] I have my gov.scot email address public on my GitHub profile
- [x] I understand I will periodically need to confirm my ongoing need for access

**Comment by tomwilsonsco** [comment]
@edtiss-scotgov you should receive an invite shortly.
